services:
  db:
    build:
      context: ./database
    container_name: my-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
      context: ./backend
    container_name: php-backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network
  nginx:
    build:
      context: ./Frontend/
    container_name: nginx_proxy
    ports:
      - "8080:80"
      - "8081:81"
      - "8082:82"
      - "8083:83"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
